# NumPy

numpy is python's package for doing math that is more advanced than +-*/

This includes special functions like cosine, exponential, sqrt, ...

On top of this we can use numpy to generate samples from many types of random variables

numpy also has a powerful data type to define vectors, matrices, and tensors

With these data types numpy also allows us to do linear algebra - matrix multiplication and matrix-vector solutions

In [2]:
# the first step of using numpy is to tell python to use it
import numpy as np

In [3]:
print(np.cos(np.pi))
print(np.sqrt(1.21))
print(np.log(np.exp(5.2)))

-1.0
1.1
5.2


In [4]:
# we can create numpy arrays by converting lists
# this is a vector
vec = np.array([1,2,3])
print(vec)
# we can create matrices by converting lists of lists
mat = np.array([[1,2,1],[4,5,9],[1,8,9]])
print('')
print(mat)
print('')
print(mat.T)

[1 2 3]

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[[1 4 1]
 [2 5 8]
 [1 9 9]]


In [5]:
# there are lots of other ways to create numpy arrays
vec2 = np.arange(0,15)
print(vec2)
print('')
vec3 = np.arange(3,21,6)
print(vec3)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

[ 3  9 15]


In [6]:

vec4 = np.linspace(0,5,10)
print(vec4)
print('')
print(vec4.reshape(5,2))
vec4_reshaped = vec4.reshape(5,2)
print(vec4_reshaped)
print(vec4)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [7]:
mat2 = np.zeros([5,3])
print(mat2)
mat3 = np.ones((3,5))
print('')
print(mat3)
mat4 = np.eye(5)
print('')
print(mat4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [8]:
# we can +-*/ arrays together if they're the right size
vec5 = np.arange(1,6)
vec6 = np.arange(3,8)
print(vec5)
print(vec6)
print(vec5+vec6)
print(vec5*vec6)
print(1/vec5)
print(np.sqrt(vec6))

[1 2 3 4 5]
[3 4 5 6 7]
[ 4  6  8 10 12]
[ 3  8 15 24 35]
[1.         0.5        0.33333333 0.25       0.2       ]
[1.73205081 2.         2.23606798 2.44948974 2.64575131]


In [9]:
# we can do matrix multiplication
print(mat)
print('')
print(vec)
print()
product = np.matmul(mat,vec)
print(product)

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[1 2 3]

[ 8 41 44]


In [10]:
print(np.linalg.solve(mat,product))
print('')
print(np.linalg.inv(mat))

[1. 2. 3.]

[[ 0.5         0.18518519 -0.24074074]
 [ 0.5        -0.14814815  0.09259259]
 [-0.5         0.11111111  0.05555556]]


In [11]:
# we can find the unique values in an array
vec7 = np.array(['blue','red','orange','purple','purple','orange','Red',6])
print(vec7)
print(np.unique(vec7))

['blue' 'red' 'orange' 'purple' 'purple' 'orange' 'Red' '6']
['6' 'Red' 'blue' 'orange' 'purple' 'red']


In [12]:
# we can also use numpy to generate samples of a random variable
rand_mat = np.random.rand(5,5) # uniform random variable
print(rand_mat)
rand_mat2 = np.random.randn(10,5) # standard normal random variable
print('')
print(rand_mat2)

[[0.1869261  0.89743932 0.92599989 0.04212799 0.21296529]
 [0.36511575 0.61779056 0.48164907 0.82231083 0.57688326]
 [0.76362223 0.36927122 0.05114045 0.4805342  0.43202456]
 [0.07057861 0.19813983 0.16206295 0.95636975 0.01728677]
 [0.44651049 0.05701866 0.92027024 0.03756307 0.91624585]]

[[ 0.56185339  1.70738606  0.16667725  1.57646393 -1.56647736]
 [ 0.53253121  1.15348794 -0.46133373  0.95470737 -0.13806835]
 [ 0.06759012  0.4308748   1.13413785 -0.83231868  0.25719968]
 [-0.67763299  1.12964164 -0.82859044 -1.6359646  -0.59509204]
 [ 1.29944925 -0.52838233  2.33630218  0.96478253  0.34788099]
 [-0.2190776  -0.163042    0.90698822  1.04964344 -0.65493404]
 [-0.31897312 -2.04664918 -0.81438981 -0.8121652  -0.03053575]
 [ 1.32207256 -1.92857701 -0.43130647  1.2418541  -1.21374914]
 [ 0.56083461 -0.2414827  -0.21686421 -0.29015129 -1.07859682]
 [-1.07054591 -1.52347217 -0.06900897  1.20600977 -0.97929696]]


In [13]:
# we can also use numpy for statistical tools on arrays
print(np.mean(rand_mat))
print(np.std(rand_mat2))

0.44031387788796406
1.0137084782626533


In [14]:
print(np.min(rand_mat))
print(np.max(rand_mat2))

0.01728676526702655
2.336302182253085


In [ ]:
# break here for next video!

In [15]:
# how do we access entries in a numpy vector
rand_vec = np.random.randn(19)
print(rand_vec)
print(rand_vec[6])

[ 0.16807182 -0.12770002 -0.56447637 -0.2149536   0.53242553 -0.49361422
  0.67958578 -0.22220712 -0.05024021  1.80994977 -0.34501288  0.68697229
 -1.05350906  0.44803643  0.88853382 -2.3871388   1.5340749   0.8592969
 -0.82479462]
0.6795857794813608


In [16]:
# we can access multiple entries at once using :
print(rand_vec[4:9])

[ 0.53242553 -0.49361422  0.67958578 -0.22220712 -0.05024021]


In [17]:
# we can also access multiple non-consecutive entries using np.arange
print(np.arange(0,15,3))
print(rand_vec[np.arange(0,15,3)])

[ 0  3  6  9 12]
[ 0.16807182 -0.2149536   0.67958578  1.80994977 -1.05350906]


In [18]:
# what about matrices
print(rand_mat)
print(rand_mat[1][2])
print(rand_mat[1,2])


[[0.1869261  0.89743932 0.92599989 0.04212799 0.21296529]
 [0.36511575 0.61779056 0.48164907 0.82231083 0.57688326]
 [0.76362223 0.36927122 0.05114045 0.4805342  0.43202456]
 [0.07057861 0.19813983 0.16206295 0.95636975 0.01728677]
 [0.44651049 0.05701866 0.92027024 0.03756307 0.91624585]]
0.4816490674373545
0.4816490674373545


In [19]:
print(rand_mat[0:2,1:3])

[[0.89743932 0.92599989]
 [0.61779056 0.48164907]]


In [20]:
# let's change some values in an array!
print(rand_vec)
rand_vec[3:5] = 4
print('')
print(rand_vec)
rand_vec[3:5] = [1,2]
print('')
print(rand_vec)

[ 0.16807182 -0.12770002 -0.56447637 -0.2149536   0.53242553 -0.49361422
  0.67958578 -0.22220712 -0.05024021  1.80994977 -0.34501288  0.68697229
 -1.05350906  0.44803643  0.88853382 -2.3871388   1.5340749   0.8592969
 -0.82479462]

[ 0.16807182 -0.12770002 -0.56447637  4.          4.         -0.49361422
  0.67958578 -0.22220712 -0.05024021  1.80994977 -0.34501288  0.68697229
 -1.05350906  0.44803643  0.88853382 -2.3871388   1.5340749   0.8592969
 -0.82479462]

[ 0.16807182 -0.12770002 -0.56447637  1.          2.         -0.49361422
  0.67958578 -0.22220712 -0.05024021  1.80994977 -0.34501288  0.68697229
 -1.05350906  0.44803643  0.88853382 -2.3871388   1.5340749   0.8592969
 -0.82479462]


In [21]:
print(rand_mat)
rand_mat[1:3,3:5] = 0
print('')
print(rand_mat)

[[0.1869261  0.89743932 0.92599989 0.04212799 0.21296529]
 [0.36511575 0.61779056 0.48164907 0.82231083 0.57688326]
 [0.76362223 0.36927122 0.05114045 0.4805342  0.43202456]
 [0.07057861 0.19813983 0.16206295 0.95636975 0.01728677]
 [0.44651049 0.05701866 0.92027024 0.03756307 0.91624585]]

[[0.1869261  0.89743932 0.92599989 0.04212799 0.21296529]
 [0.36511575 0.61779056 0.48164907 0.         0.        ]
 [0.76362223 0.36927122 0.05114045 0.         0.        ]
 [0.07057861 0.19813983 0.16206295 0.95636975 0.01728677]
 [0.44651049 0.05701866 0.92027024 0.03756307 0.91624585]]


In [22]:
sub_mat = rand_mat[0:2,0:3]
print(sub_mat)
sub_mat[:] = 3
print(sub_mat)


[[0.1869261  0.89743932 0.92599989]
 [0.36511575 0.61779056 0.48164907]]
[[3. 3. 3.]
 [3. 3. 3.]]


In [23]:
print(rand_mat)

[[3.         3.         3.         0.04212799 0.21296529]
 [3.         3.         3.         0.         0.        ]
 [0.76362223 0.36927122 0.05114045 0.         0.        ]
 [0.07057861 0.19813983 0.16206295 0.95636975 0.01728677]
 [0.44651049 0.05701866 0.92027024 0.03756307 0.91624585]]


In [ ]:
sub_mat2 = rand_mat[0:2,0:3].copy()
sub_mat2[:] = 99
print(sub_mat2)
print(rand_mat)


In [ ]:
# break here for next video

In [24]:
# we can also access entries with logicals
rand_vec = np.random.randn(15)

print(rand_vec)
print(rand_vec>0)
print(rand_vec[rand_vec>0])

[-2.98157112e+00  1.16931477e+00 -8.17905375e-01  1.56022141e+00
 -1.56587726e-01  1.34546554e+00 -9.34689612e-01  1.12477236e+00
 -5.99064744e-01 -3.02248723e-02  6.21822616e-01  2.69008878e+00
 -4.17321106e-01 -2.27286753e-04 -2.94886526e-01]
[False  True False  True False  True False  True False False  True  True
 False False False]
[1.16931477 1.56022141 1.34546554 1.12477236 0.62182262 2.69008878]


In [25]:
print(rand_mat2)
print(rand_mat2[rand_mat2>0])

[[ 0.56185339  1.70738606  0.16667725  1.57646393 -1.56647736]
 [ 0.53253121  1.15348794 -0.46133373  0.95470737 -0.13806835]
 [ 0.06759012  0.4308748   1.13413785 -0.83231868  0.25719968]
 [-0.67763299  1.12964164 -0.82859044 -1.6359646  -0.59509204]
 [ 1.29944925 -0.52838233  2.33630218  0.96478253  0.34788099]
 [-0.2190776  -0.163042    0.90698822  1.04964344 -0.65493404]
 [-0.31897312 -2.04664918 -0.81438981 -0.8121652  -0.03053575]
 [ 1.32207256 -1.92857701 -0.43130647  1.2418541  -1.21374914]
 [ 0.56083461 -0.2414827  -0.21686421 -0.29015129 -1.07859682]
 [-1.07054591 -1.52347217 -0.06900897  1.20600977 -0.97929696]]
[0.56185339 1.70738606 0.16667725 1.57646393 0.53253121 1.15348794
 0.95470737 0.06759012 0.4308748  1.13413785 0.25719968 1.12964164
 1.29944925 2.33630218 0.96478253 0.34788099 0.90698822 1.04964344
 1.32207256 1.2418541  0.56083461 1.20600977]


In [26]:

print(rand_vec)
print('')
rand_vec[rand_vec>0.5] = -5
print(rand_vec)

[-2.98157112e+00  1.16931477e+00 -8.17905375e-01  1.56022141e+00
 -1.56587726e-01  1.34546554e+00 -9.34689612e-01  1.12477236e+00
 -5.99064744e-01 -3.02248723e-02  6.21822616e-01  2.69008878e+00
 -4.17321106e-01 -2.27286753e-04 -2.94886526e-01]

[-2.98157112e+00 -5.00000000e+00 -8.17905375e-01 -5.00000000e+00
 -1.56587726e-01 -5.00000000e+00 -9.34689612e-01 -5.00000000e+00
 -5.99064744e-01 -3.02248723e-02 -5.00000000e+00 -5.00000000e+00
 -4.17321106e-01 -2.27286753e-04 -2.94886526e-01]


In [27]:
# let's save some arrays on the disk for use later!
np.save('saved_file_name',rand_mat2)


In [28]:
np.savez('zipped_file_name',rand_mat=rand_mat,rand_mat2=rand_mat2)

In [29]:
# now let's load it
loaded_vec = np.load('saved_file_name.npy')
loaded_zip = np.load('zipped_file_name.npz')

print(loaded_vec)
print('')
print(loaded_zip)

[[ 0.56185339  1.70738606  0.16667725  1.57646393 -1.56647736]
 [ 0.53253121  1.15348794 -0.46133373  0.95470737 -0.13806835]
 [ 0.06759012  0.4308748   1.13413785 -0.83231868  0.25719968]
 [-0.67763299  1.12964164 -0.82859044 -1.6359646  -0.59509204]
 [ 1.29944925 -0.52838233  2.33630218  0.96478253  0.34788099]
 [-0.2190776  -0.163042    0.90698822  1.04964344 -0.65493404]
 [-0.31897312 -2.04664918 -0.81438981 -0.8121652  -0.03053575]
 [ 1.32207256 -1.92857701 -0.43130647  1.2418541  -1.21374914]
 [ 0.56083461 -0.2414827  -0.21686421 -0.29015129 -1.07859682]
 [-1.07054591 -1.52347217 -0.06900897  1.20600977 -0.97929696]]



In [30]:
print(loaded_zip['rand_mat'])
print('')
print(loaded_zip['rand_mat2'])

new_array  = loaded_zip['rand_mat']
print(new_array)

[[3.         3.         3.         0.04212799 0.21296529]
 [3.         3.         3.         0.         0.        ]
 [0.76362223 0.36927122 0.05114045 0.         0.        ]
 [0.07057861 0.19813983 0.16206295 0.95636975 0.01728677]
 [0.44651049 0.05701866 0.92027024 0.03756307 0.91624585]]

[[ 0.56185339  1.70738606  0.16667725  1.57646393 -1.56647736]
 [ 0.53253121  1.15348794 -0.46133373  0.95470737 -0.13806835]
 [ 0.06759012  0.4308748   1.13413785 -0.83231868  0.25719968]
 [-0.67763299  1.12964164 -0.82859044 -1.6359646  -0.59509204]
 [ 1.29944925 -0.52838233  2.33630218  0.96478253  0.34788099]
 [-0.2190776  -0.163042    0.90698822  1.04964344 -0.65493404]
 [-0.31897312 -2.04664918 -0.81438981 -0.8121652  -0.03053575]
 [ 1.32207256 -1.92857701 -0.43130647  1.2418541  -1.21374914]
 [ 0.56083461 -0.2414827  -0.21686421 -0.29015129 -1.07859682]
 [-1.07054591 -1.52347217 -0.06900897  1.20600977 -0.97929696]]
[[3.         3.         3.         0.04212799 0.21296529]
 [3.         3.    

In [31]:
# we can also save/load as text files...but only single variables
np.savetxt('text_file_name.txt',rand_mat,delimiter=',')
rand_mat_txt = np.loadtxt('text_file_name.txt',delimiter=',')
print(rand_mat)
print('')
print(rand_mat_txt)

[[3.         3.         3.         0.04212799 0.21296529]
 [3.         3.         3.         0.         0.        ]
 [0.76362223 0.36927122 0.05114045 0.         0.        ]
 [0.07057861 0.19813983 0.16206295 0.95636975 0.01728677]
 [0.44651049 0.05701866 0.92027024 0.03756307 0.91624585]]

[[3.         3.         3.         0.04212799 0.21296529]
 [3.         3.         3.         0.         0.        ]
 [0.76362223 0.36927122 0.05114045 0.         0.        ]
 [0.07057861 0.19813983 0.16206295 0.95636975 0.01728677]
 [0.44651049 0.05701866 0.92027024 0.03756307 0.91624585]]
