In [27]:
import numpy as np

#how to access entries in array

# generate random values array 

randArr = np.random.randn(10)

print(f'total values in randArr : {len(randArr)}')
print(f'randArr {randArr}')

print(f'6th element is {round(randArr[5],2)}')


total values in randArr : 10
randArr [-0.71975477  1.13923864 -2.70813563  2.60208218  0.11350925  0.62276331
 -0.61466324  1.79131215  0.9979614   1.44166495]
6th element is 0.62


In [16]:
print(randArr[1:3]) #Accessing Subset

[1.04423722 3.1188297 ]


In [17]:
print(randArr[np.arange(0,10,3)]) ## accessing multiple random entries

[ 0.39485667  0.40609696 -1.71222552 -0.72018928]


In [36]:
rand_mat = randArr.reshape(5,2)
print(rand_mat)

print('\n\n')

print(rand_mat[2,1]) ## accessing 2d array 

print(rand_mat[2][1]) #Alternate 
print()
## submatrix access 

print(rand_mat[0:3,0:2])


[[-0.71975477  4.        ]
 [ 4.          2.60208218]
 [ 0.11350925  0.62276331]
 [-0.61466324  1.79131215]
 [ 0.9979614   1.44166495]]



0.6227633107451389
0.6227633107451389

[[-0.71975477  4.        ]
 [ 4.          2.60208218]
 [ 0.11350925  0.62276331]]


In [41]:
#Changing Values in Array 
print(f'\nbefore changes randArr {randArr}')
randArr[1:3] = 4
print(f'\n\nafter changes randArr {randArr}')  # or 

# or matrix 

rand_mat[0:3,0:2] = 0.0
print()
print(rand_mat)

## create sub matrix 

sub_mat  = rand_mat[0:3,0:2]
sub_mat[:] = 3.14 #all values of the array
print()
print(sub_mat)
print()
print(rand_mat) ## changrs value in original

#use copy to avoid overwrite 

sub_mat2  = rand_mat[0:3,0:2].copy()

sub_mat2[:] = 9.14 #all values of the array
print()
print(sub_mat2)
print()
print(rand_mat) # orignal values does not impact



before changes randArr [ 3.14        3.14        3.14        3.14        3.14        3.14
 -0.61466324  1.79131215  0.9979614   1.44166495]


after changes randArr [ 3.14        4.          4.          3.14        3.14        3.14
 -0.61466324  1.79131215  0.9979614   1.44166495]

[[ 0.          0.        ]
 [ 0.          0.        ]
 [ 0.          0.        ]
 [-0.61466324  1.79131215]
 [ 0.9979614   1.44166495]]

[[3.14 3.14]
 [3.14 3.14]
 [3.14 3.14]]

[[ 3.14        3.14      ]
 [ 3.14        3.14      ]
 [ 3.14        3.14      ]
 [-0.61466324  1.79131215]
 [ 0.9979614   1.44166495]]

[[9.14 9.14]
 [9.14 9.14]
 [9.14 9.14]]

[[ 3.14        3.14      ]
 [ 3.14        3.14      ]
 [ 3.14        3.14      ]
 [-0.61466324  1.79131215]
 [ 0.9979614   1.44166495]]
