In [2]:
import numpy as np

#generate random array 
randVec = np.random.randn(15)

#print values 
print("all values in array")

print(randVec)

print()


randMat2 = randVec.reshape(5,3)
print("all values in 5*3 2d matrix \n\n")

print(randMat2)


all values in array
[-1.39787623 -0.00445698  0.78861907 -0.67877643  0.11375186 -0.21798769
 -1.69094232  0.94426904  0.98453892 -0.77892855 -0.01347021  0.335829
 -0.51695812 -0.89630667 -0.00863994]

all values in 5*3 2d matrix 


[[-1.39787623 -0.00445698  0.78861907]
 [-0.67877643  0.11375186 -0.21798769]
 [-1.69094232  0.94426904  0.98453892]
 [-0.77892855 -0.01347021  0.335829  ]
 [-0.51695812 -0.89630667 -0.00863994]]


In [9]:
# save arrays, save method save only one array at a time 


np.save('save_1d_array_eg',randVec)
np.save('save_2d_array_eg',randMat2)

In [6]:
#saving multiple times in zip 
#zipname, file_under_zip, which array to store 
np.savez('save_zip_array_eg', rand_1d=randVec, rand_2d=randMat2)

In [19]:
#loading files that saved with save method

load1D = np.load('save_1d_array_eg.npy')
load2D = np.load('save_2d_array_eg.npy')

print('data from saved files')

print()

print(load1D)

print()

print(load2D)


data from saved files

[-1.39787623 -0.00445698  0.78861907 -0.67877643  0.11375186 -0.21798769
 -1.69094232  0.94426904  0.98453892 -0.77892855 -0.01347021  0.335829
 -0.51695812 -0.89630667 -0.00863994]

[[-1.39787623 -0.00445698  0.78861907]
 [-0.67877643  0.11375186 -0.21798769]
 [-1.69094232  0.94426904  0.98453892]
 [-0.77892855 -0.01347021  0.335829  ]
 [-0.51695812 -0.89630667 -0.00863994]]


In [18]:
#loading files that saved with savez method

loadedZip = np.load('save_zip_array_eg.npz')

print('data from zip files')

print(loadedZip)

print()

print(loadedZip['rand_1d'])
print()

print(loadedZip['rand_2d'])


data from zip files

[-1.39787623 -0.00445698  0.78861907 -0.67877643  0.11375186 -0.21798769
 -1.69094232  0.94426904  0.98453892 -0.77892855 -0.01347021  0.335829
 -0.51695812 -0.89630667 -0.00863994]

[[-1.39787623 -0.00445698  0.78861907]
 [-0.67877643  0.11375186 -0.21798769]
 [-1.69094232  0.94426904  0.98453892]
 [-0.77892855 -0.01347021  0.335829  ]
 [-0.51695812 -0.89630667 -0.00863994]]


In [22]:
#saving data as text file 

np.savetxt('save_1d_array_eg.txt',randVec,delimiter=',')
np.savetxt('save_2d_array_eg.txt',randMat2,delimiter=',')
np.savetxt('save_1d_array_eg.csv',randVec,delimiter=',')

#loading txt files


load1D = np.loadtxt('save_1d_array_eg.txt',delimiter=',')
load2D = np.loadtxt('save_2d_array_eg.txt',delimiter=',')


print('data from saved files')

print()

print(load1D)

print()

print(load2D)


data from saved files

[-1.39787623 -0.00445698  0.78861907 -0.67877643  0.11375186 -0.21798769
 -1.69094232  0.94426904  0.98453892 -0.77892855 -0.01347021  0.335829
 -0.51695812 -0.89630667 -0.00863994]

[[-1.39787623 -0.00445698  0.78861907]
 [-0.67877643  0.11375186 -0.21798769]
 [-1.69094232  0.94426904  0.98453892]
 [-0.77892855 -0.01347021  0.335829  ]
 [-0.51695812 -0.89630667 -0.00863994]]
