In [15]:
import numpy as np

#generate random array 
randVec = np.random.randn(15)

#print values 
print("all values in array")

print(randVec)

print()

print("all values in array > 0")
#access items only >0
#returns boolean array marked with values true or false for condtions given 
print(randVec>0)

print()
print("subset array with has values > 0")
#Create subset with condition
print(randVec[randVec>0])

      


all values in array
[ 0.68181677  0.15788573 -0.22833189 -3.76046283  0.4398243  -0.13337324
 -0.92331963 -0.19116619 -2.05980584 -1.12545759  0.61364197  0.44533065
 -0.84212361 -0.32076884  2.05233071]

all values in array > 0
[ True  True False False  True False False False False False  True  True
 False False  True]

subset array with has values > 0
[0.68181677 0.15788573 0.4398243  0.61364197 0.44533065 2.05233071]


In [14]:

#print values 
print("all values in array\n\n")

print(randVec)

#Operations on Matrix

randMat2 = randVec.reshape(5,3)
print("all values in 5*3 2d matrix \n\n")

print(randMat2)



print("\n\nall values in 5*3 2d matrix subset array with has values > 1\n\n")

print(randMat2[randMat2>1])


all values in array


[ 0.75384494  1.2364606   0.50052309 -1.71598928  1.01092424  1.66452561
 -0.06737139 -0.3527547   1.04162165  0.43709723  1.25508685 -0.30461117
  0.01234181 -0.34963729 -1.05647318]
all values in 5*3 2d matrix 


[[ 0.75384494  1.2364606   0.50052309]
 [-1.71598928  1.01092424  1.66452561]
 [-0.06737139 -0.3527547   1.04162165]
 [ 0.43709723  1.25508685 -0.30461117]
 [ 0.01234181 -0.34963729 -1.05647318]]


all values in 5*3 2d matrix subset array with has values > 1


[1.2364606  1.01092424 1.66452561 1.04162165 1.25508685]


In [19]:
#print values 
print("all values in array\n\n")

print(randVec)

#update values based on logical indexing
randVec[randVec>0] = 2

print("\n\nall values in array after updates \n\n")
print(randVec)



all values in array


[ 0.68181677  0.15788573 -0.22833189 -3.76046283  0.4398243  -0.13337324
 -0.92331963 -0.19116619 -2.05980584 -1.12545759  0.61364197  0.44533065
 -0.84212361 -0.32076884  2.        ]


all values in array after updates 


[ 2.          2.         -0.22833189 -3.76046283  2.         -0.13337324
 -0.92331963 -0.19116619 -2.05980584 -1.12545759  2.          2.
 -0.84212361 -0.32076884  2.        ]
