In [1]:
import numpy as np

print(f'using numpy version : {np.__version__}')

using numpy version : 1.20.1


In [4]:
myList = [1,2,3,4,3,2,1]

print(f'my list is {myList}')

npList = np.array(myList)

print(f'list converted to np array is {npList}')


#NP Operations 

print(f'{npList} * 10 is {npList * 10}')




my list is [1, 2, 3, 4, 3, 2, 1]
list converted to np array is [1 2 3 4 3 2 1]
[1 2 3 4 3 2 1] * 10 is [10 20 30 40 30 20 10]


In [8]:
myTuple = (1,2,3,4,3,2,1.0,10.2)

print(f'my typle is {myTuple}')

npTuple = np.array(myTuple)

print(f'tuple converted to np array is {npTuple}')

#NP Operations 

print(f'{myTuple} / 10.2 is {npTuple / 10.2}')

my typle is (1, 2, 3, 4, 3, 2, 1.0, 10.2)
tuple converted to np array is [ 1.   2.   3.   4.   3.   2.   1.  10.2]
(1, 2, 3, 4, 3, 2, 1.0, 10.2) / 10.2 is [0.09803922 0.19607843 0.29411765 0.39215686 0.29411765 0.19607843
 0.09803922 1.        ]


In [20]:

myArray = np.linspace(7,100, 7)

# finding length fo array using len
print(f'using len {len(myArray)}, myArray {myArray}')

# or 


print(f'using size {myArray.size}')



using len 7, myArray [  7.   22.5  38.   53.5  69.   84.5 100. ]
using size 7


## linspace, zeros,ones

In [44]:
#myArray = np.linspace(1,11,2)

myArray = np.linspace(1,11,5,dtype=int)

print(f'myArray is {myArray}, type is {type(myArray)}')
for i in myArray : 
    print(f'value of i is {i}, type is {type(i)}')

myArray is [ 1  3  6  8 11], type is <class 'numpy.ndarray'>
value of i is 1, type is <class 'numpy.int64'>
value of i is 3, type is <class 'numpy.int64'>
value of i is 6, type is <class 'numpy.int64'>
value of i is 8, type is <class 'numpy.int64'>
value of i is 11, type is <class 'numpy.int64'>


In [36]:
myArray = np.zeros(10)

print(f'myArray is {myArray}, type is {type(myArray)}')
for i in myArray : 
    print(f'value of i is {i}, type is {type(i)}')

myArray is [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], type is <class 'numpy.ndarray'>
value of i is 0.0, type is <class 'numpy.float64'>
value of i is 0.0, type is <class 'numpy.float64'>
value of i is 0.0, type is <class 'numpy.float64'>
value of i is 0.0, type is <class 'numpy.float64'>
value of i is 0.0, type is <class 'numpy.float64'>
value of i is 0.0, type is <class 'numpy.float64'>
value of i is 0.0, type is <class 'numpy.float64'>
value of i is 0.0, type is <class 'numpy.float64'>
value of i is 0.0, type is <class 'numpy.float64'>
value of i is 0.0, type is <class 'numpy.float64'>


In [37]:
myArray = np.ones(10)

print(f'myArray is {myArray}, type is {type(myArray)}')
for i in myArray : 
    print(f'value of i is {i}, type is {type(i)}')

myArray is [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.], type is <class 'numpy.ndarray'>
value of i is 1.0, type is <class 'numpy.float64'>
value of i is 1.0, type is <class 'numpy.float64'>
value of i is 1.0, type is <class 'numpy.float64'>
value of i is 1.0, type is <class 'numpy.float64'>
value of i is 1.0, type is <class 'numpy.float64'>
value of i is 1.0, type is <class 'numpy.float64'>
value of i is 1.0, type is <class 'numpy.float64'>
value of i is 1.0, type is <class 'numpy.float64'>
value of i is 1.0, type is <class 'numpy.float64'>
value of i is 1.0, type is <class 'numpy.float64'>


In [39]:
myArray = np.zeros((5,3))

print(f'myArray is {myArray}, type is {type(myArray)}')


myArray is [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], type is <class 'numpy.ndarray'>
value of i is [0. 0. 0.], type is <class 'numpy.ndarray'>
value of i is [0. 0. 0.], type is <class 'numpy.ndarray'>
value of i is [0. 0. 0.], type is <class 'numpy.ndarray'>
value of i is [0. 0. 0.], type is <class 'numpy.ndarray'>
value of i is [0. 0. 0.], type is <class 'numpy.ndarray'>


In [47]:
myArray = np.zeros((5,3,2))

print(f'myArray is {myArray}, type is {type(myArray)}')

myArray is [[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]], type is <class 'numpy.ndarray'>


## Index, Slice & Iterate

In [56]:
myList = [1,2,3,4,3,2,1]

npList = np.array(myList)

print(f'np array is {npList}')

npList[0] = npList[0] * 10

print(f'np array is {npList} - after updating 0 index ')

np array is [1 2 3 4 3 2 1]
np array is [10  2  3  4  3  2  1] - after updating 0 index 


In [65]:
# 3 D Arrays 

npList = np.arange(70)
npList.shape = (2,7,5)

print(f'np array is {npList}')


np array is [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]]

 [[35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]
  [60 61 62 63 64]
  [65 66 67 68 69]]]


## Boolean mask arrays




In [77]:
npList = np.arange(0,26,3)
print(f'np array is {npList}')

div_by_5 = 0 == (npList%5)

print(f'np div_by_5 is {div_by_5}')

## fetching only true items 
div_by_5_items = npList[div_by_5]

print(f'np div_by_5_items is {div_by_5_items}')


np array is [ 0  3  6  9 12 15 18 21 24]
np div_by_5 is [ True False False False False  True False False False]
np div_by_5_items is [ 0 15]


## Logical Operators


In [ ]:
mod_test = 0 == (npList%5)
