In [8]:
import numpy as np #import numpy

print(f'Pi Value is {round(np.pi,4)}')

Pi Value is 3.1416


In [16]:
nums = [1,2,3,4,5,6]
nums2D = [[1,2,3],[1,2,3],[1,2,3]]

vec = np.array(nums)

mat = np.array(nums2D)

print(f'Type of Vec array is {type(vec)}, {vec}')

print(f'Type of Mat array is {type(mat)},\n {mat}, \n\n transpose is \n {mat.T}')

Type of Vec array is <class 'numpy.ndarray'>, [1 2 3 4 5 6]
Type of Mat array is <class 'numpy.ndarray'>,
 [[1 2 3]
 [1 2 3]
 [1 2 3]], 

 transpose is 
 [[1 1 1]
 [2 2 2]
 [3 3 3]]


In [26]:
# creating arrays using numpy

vec2 = np.arange(0,15,2)
vec3 = np.arange(0,30,4)

print(f'vec2 is {vec2}, vec3 is {vec3}')

for i in np.arange(0,30,np.pi):
    print(f'i is {i}, type of i is {type(i)}')


vec2 is [ 0  2  4  6  8 10 12 14], vec3 is [ 0  4  8 12 16 20 24 28]
i is 0.0, type of i is <class 'numpy.float64'>
i is 3.141592653589793, type of i is <class 'numpy.float64'>
i is 6.283185307179586, type of i is <class 'numpy.float64'>
i is 9.42477796076938, type of i is <class 'numpy.float64'>
i is 12.566370614359172, type of i is <class 'numpy.float64'>
i is 15.707963267948966, type of i is <class 'numpy.float64'>
i is 18.84955592153876, type of i is <class 'numpy.float64'>
i is 21.991148575128552, type of i is <class 'numpy.float64'>
i is 25.132741228718345, type of i is <class 'numpy.float64'>
i is 28.274333882308138, type of i is <class 'numpy.float64'>


In [62]:
vec4 = np.linspace(1,10,10) #linear spacing 
print(vec4)
#Convert to matrix 
try:
    newMat = vec4.reshape(2,5)
    print(f'converted to matrix is \n {newMat}, type is {type(newMat)}')
except Exception as valErr:
    print(f'invalid matrix configuration for input error : {valErr}')
else:
    print(f'process completed with no errors')
finally:
    print(f'always execute');

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
converted to matrix is 
 [[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]], type is <class 'numpy.ndarray'>
process completed with no errors
always execute


In [67]:
#creare matrix zeros

matZeros = np.zeros((3,5))

print(f'matZeros type is {type(matZeros)}, and values \n {matZeros}')

matOnes= np.ones((3,5))

print(f'matOnes type is {type(matOnes)}, and values \n {matOnes}')

matEye = np.eye(5)

print(f'matEye type is {type(matEye)}, and values \n {matEye}')

matZeros type is <class 'numpy.ndarray'>, and values 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
matOnes type is <class 'numpy.ndarray'>, and values 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
matEye type is <class 'numpy.ndarray'>, and values 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [74]:
vec5 = np.arange(1,6)
vec6 = np.arange(3,8)

print(f'vec5 is {vec5}, vec6 is {vec6}, add is {vec5+vec6}, product is {vec5*vec6}, division is {vec6/vec5}')

print(f'1/vec5 is {1/vec5}')


print(f'vec5 square is {np.square(vec5)}')



vec5 is [1 2 3 4 5], vec6 is [3 4 5 6 7], add is [ 4  6  8 10 12], product is [ 3  8 15 24 35], division is [3.         2.         1.66666667 1.5        1.4       ]
1/vec5 is [1.         0.5        0.33333333 0.25       0.2       ]
vec5 square is [ 1  4  9 16 25]


In [80]:
nums = [1,2,3]
nums2D = [[1,2,3],[1,2,3],[1,2,3]]

vec = np.array(nums)

mat = np.array(nums2D)


print(f'Type of Vec array is {type(vec)}, {vec}')

print(f'Type of Mat array is {type(mat)},\n {mat}')

product = np.matmul(vec,mat)

print(f'Type of product array is {type(product)},\n {product}')

Type of Vec array is <class 'numpy.ndarray'>, [1 2 3]
Type of Mat array is <class 'numpy.ndarray'>,
 [[1 2 3]
 [1 2 3]
 [1 2 3]]
Type of product array is <class 'numpy.ndarray'>,
 [ 6 12 18]


In [89]:
vec7 = np.array (('apple','manago', 'orange',5,6,7,5,6,7,'apple', 'Apple')) 

print(vec7)
print(np.unique(vec7))


['apple' 'manago' 'orange' '5' '6' '7' '5' '6' '7' 'apple' 'Apple']
['5' '6' '7' 'Apple' 'apple' 'manago' 'orange']


In [98]:
rand_mat = np.random.rand(5,5)
print(rand_mat)

rand_mat2 = np.random.randn(10,5)
print(rand_mat2)


print(f'\n\nmean value of rand_mat2 is {np.mean(rand_mat2)}')
print(f'\n\nst deviatiom of rand_mat2 is {np.std(rand_mat2)}')

print(f'\n\nmin value of rand_mat2 is {np.min(rand_mat2)}')
print(f'\n\nmax of rand_mat2 is {np.max(rand_mat2)}')




[[0.59881183 0.56235441 0.34586273 0.41547038 0.14729619]
 [0.41628913 0.58238115 0.51435221 0.39638592 0.42590793]
 [0.74967154 0.56116343 0.08361933 0.10192355 0.52755972]
 [0.51789821 0.24543789 0.49923416 0.81870136 0.44059115]
 [0.83348013 0.85845974 0.5269743  0.34909756 0.94199876]]
[[-0.94489142  0.3998641   0.31504573  0.11349275  1.22462186]
 [-0.7421671  -0.38167842  1.09939699  0.14058841 -0.15431149]
 [ 2.15482895 -0.07977703  0.73329943 -0.99418645  0.17578522]
 [-1.54448437  2.04302385 -0.49726381 -0.02852713 -0.4425285 ]
 [ 1.13099768 -1.40891521 -0.34174848  1.28627565 -1.03636351]
 [-0.30214017  0.52498793  0.49006367  0.10071972 -0.65475614]
 [-0.15396699 -0.25929543 -0.46797311  0.94639004  0.55467252]
 [ 1.31331021  0.05774789  1.29177102 -0.08609436 -1.60658154]
 [-0.33342692 -0.13406038 -1.08874354  0.1617839   0.16943476]
 [-0.85968498  0.24331518  0.04653681 -0.43112204 -0.91592034]]


mean value of rand_mat2 is 0.01654690782845909


st deviatiom of rand_mat2 i